=== katherinelc321/ARO-HCP/config/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "object",
    "properties": {
      "aksName": {
        "type": "string"
      },
      "aroDevopsMsiId": {
        "type": "string"
      },
      "baseDnsZoneName": {
        "type": "string"
      },
      "baseDnsZoneRG": {
        "type": "string"
      },
      "clusterService": {
        "type": "object",
        "properties": {
          "acrRG": {
            "type": "string"
          },
          "imageRepo": {
            "type": "string"
          },
          "imageTag": {
            "type": "string"
          },
          "postgres": {
            "type": "object",
            "properties": {
              "deploy": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              },
              "minTLSVersion": {
                "type": "string",
                "enum": ["TLSV1.2", "TLSV1.3"]
              }
            },
            "required": [
              "deploy",
              "name",
              "private",
              "minTLSVersion"
            ]
          },
          "azureOperatorsManagedIdentitiesConfig":{
            "type": "string" 
          }
        },
        "additionalProperties": false,
        "required": [
          "acrRG",
          "imageRepo",
          "imageTag",
          "postgres"
        ]
      },
      "cxKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "softDelete"
        ]
      },
      "extraVars": {
        "type": "object",
        "properties": {},
        "required": []
      },
      "firstPartyAppClientId": {
        "type": "string"
      },
      "miMockClientId": {
        "type": "string"
      },
      "miMockPrincipalId": {
        "type": "string"
      },
      "armHelperClientId": {
        "type": "string"
      },
      "armHelperFPAPrincipalId": {
        "type": "string"
      },
      "backend": {
        "type": "object",
        "properties": {
          "imageTag": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "imageTag"
        ]
      },
      "frontend": {
        "type": "object",
        "properties": {
          "imageTag": {
            "type": "string"
          },
          "cosmosDB": {
            "type": "object",
            "properties": {
              "deploy": {
                "type": "boolean"
              },
              "disableLocalAuth": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "deploy",
              "disableLocalAuth",
              "name",
              "private"
            ]
          },
          "cert": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "name"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "imageTag",
          "cosmosDB",
          "cert"
        ]
      },
      "global": {
        "type": "object",
        "properties": {
          "rg": {
            "type": "string"
          },
          "subscription": {
            "type": "string"
          },
          "manageTokenCustomRole": {
            "type": "boolean"
          },
          "region": {
            "type": "string"
          }
        },
        "required": [
          "rg",
          "subscription",
          "manageTokenCustomRole",
          "region"
        ]
      },
      "hypershift": {
        "type": "object",
        "properties": {
          "additionalInstallArg": {
            "type": "string"
          },
          "namespace": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "additionalInstallArg",
          "namespace"
        ]
      },
      "hypershiftOperator": {
        "type": "object",
        "properties": {
          "imageTag": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "imageTag"
        ]
      },
      "imageSync": {
        "type": "object",
        "properties": {
          "acrRG": {
            "type": "string"
          },
          "environmentName": {
            "type": "string"
          },
          "componentSync": {
            "type": "object",
            "properties": {
              "bearerSecretNames": {
                "type": "array"
              },
              "enabled": {
                "type": "boolean"
              },
              "imageRepo": {
                "type": "string"
              },
              "imageTag": {
                "type": "string"
              },
              "repositories": {
                "type": "string"
              },
              "secrets": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "bearerSecretNames",
              "enabled",
              "imageRepo",
              "imageTag",
              "repositories",
              "secrets"
            ]
          },
          "ocMirror": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean"
              },
              "imageRepo": {
                "type": "string"
              },
              "imageTag": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "enabled",
              "imageRepo",
              "imageTag"
            ]
          },
          "keyVault": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              },
              "softDelete": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "name",
              "private",
              "softDelete"
            ]
          },
          "rg": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "acrRG",
          "environmentName",
          "componentSync",
          "ocMirror",
          "keyVault",
          "rg"
        ]
      },
      "istioVersion": {
        "type": "string"
      },
      "kubernetesVersion": {
        "type": "string"
      },
      "maestro": {
        "type": "object",
        "properties": {
          "certDomain": {
            "type": "string"
          },
          "consumerName": {
            "type": "string"
          },
          "serverMqttClientName": {
            "type": "string"
          },
          "eventGrid": {
            "type": "object",
            "properties": {
              "maxClientSessionsPerAuthName": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "maxClientSessionsPerAuthName",
              "name",
              "private"
            ]
          },
          "imageBase": {
            "type": "string"
          },
          "imageTag": {
            "type": "string"
          },
          "postgres": {
            "type": "object",
            "properties": {
              "deploy": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              },
              "serverStorageSizeGB": {
                "type": "integer"
              },
              "serverVersion": {
                "type": "string"
              },
              "minTLSVersion": {
                "type": "string",
                "enum": ["TLSV1.2", "TLSV1.3"]
              }
            },
            "additionalProperties": false,
            "required": [
              "deploy",
              "name",
              "private",
              "serverStorageSizeGB",
              "serverVersion",
              "minTLSVersion"
            ]
          },
          "restrictIstioIngress": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "certDomain",
          "consumerName",
          "serverMqttClientName",
          "eventGrid",
          "imageBase",
          "imageTag",
          "postgres",
          "restrictIstioIngress"
        ]
      },
      "mgmt": {
        "type": "object",
        "properties": {
          "etcd": {
            "type": "object",
            "properties": {
              "kvName": {
                "type": "string"
              },
              "kvSoftDelete": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "kvName",
              "kvSoftDelete"
            ]
          },
          "rg": {
            "type": "string"
          },
          "subscription": {
            "type": "string"
          },
          "clusterServiceResourceId": {
            "type": "string"
          },
          "systemAgentPool": {
            "type": "object",
            "properties": {
              "maxCount": {
                "type": "number"
              },
              "minCount": {
                "type": "number"
              },
              "osDiskSizeGB": {
                "type": "number"
              },
              "vmSize": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "maxCount",
              "minCount",
              "osDiskSizeGB",
              "vmSize"
            ]
          },
          "userAgentPool": {
            "type": "object",
            "properties": {
              "azCount": {
                "type": "number"
              },
              "maxCount": {
                "type": "number"
              },
              "minCount": {
                "type": "number"
              },
              "osDiskSizeGB": {
                "type": "number"
              },
              "vmSize": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "azCount",
              "maxCount",
              "minCount",
              "osDiskSizeGB",
              "vmSize"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "clusterServiceResourceId",
          "etcd",
          "rg",
          "systemAgentPool",
          "subscription",
          "userAgentPool"
        ]
      },
      "mgmtKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "softDelete"
        ]
      },
      "monitoring": {
        "type": "object",
        "properties": {
          "grafanaAdminGroupPrincipalId": {
            "type": "string"
          },
          "grafanaName": {
            "type": "string"
          },
          "msiName": {
            "type": "string"
          },
          "workspaceName": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "grafanaAdminGroupPrincipalId",
          "grafanaName",
          "msiName",
          "workspaceName"
        ]
      },
      "msiKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "softDelete"
        ]
      },
      "ocpAcrName": {
        "type": "string"
      },
      "oidcStorageAccountName": {
        "type": "string"
      },
      "podSubnetPrefix": {
        "type": "string"
      },
      "region": {
        "type": "string"
      },
      "regionRG": {
        "type": "string"
      },
      "regionalDNSSubdomain": {
        "type": "string"
      },
      "serviceKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "region": {
            "type": "string"
          },
          "rg": {
            "type": "string"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "region",
          "rg",
          "softDelete"
        ]
      },
      "subnetPrefix": {
        "type": "string"
      },
      "svc": {
        "type": "object",
        "properties": {
          "etcd": {
            "type": "object",
            "properties": {
              "kvName": {
                "type": "string"
              },
              "kvSoftDelete": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "kvName",
              "kvSoftDelete"
            ]
          },
          "userAgentPool": {
            "type": "object",
            "properties": {
              "azCount": {
                "type": "number"
              },
              "maxCount": {
                "type": "number"
              },
              "minCount": {
                "type": "number"
              },
              "osDiskSizeGB": {
                "type": "number"
              },
              "vmSize": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "azCount",
              "maxCount",
              "minCount",
              "osDiskSizeGB",
              "vmSize"
            ]
          },
          "rg": {
            "type": "string"
          },
          "subscription": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "etcd",
          "rg",
          "subscription",
          "userAgentPool"
        ]
      },
      "svcAcrName": {
        "type": "string"
      },
      "vnetAddressPrefix": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": [
      "aksName",
      "aroDevopsMsiId",
      "baseDnsZoneName",
      "baseDnsZoneRG",
      "clusterService",
      "cxKeyVault",
      "firstPartyAppClientId",
      "frontend",
      "global",
      "hypershift",
      "hypershiftOperator",
      "imageSync",
      "istioVersion",
      "kubernetesVersion",
      "maestro",
      "mgmt",
      "mgmtKeyVault",
      "monitoring",
      "msiKeyVault",
      "ocpAcrName",
      "oidcStorageAccountName",
      "podSubnetPrefix",
      "region",
      "regionRG",
      "regionalDNSSubdomain",
      "serviceKeyVault",
      "subnetPrefix",
      "svc",
      "svcAcrName",
      "vnetAddressPrefix"
    ]
  }

=== katherinelc321/ARO-HCP/config/public-cloud-dev.json
{
  "aksName": "aro-hcp-aks",
  "armHelperClientId": "2c6ca254-36bd-43c8-a7a8-fe880bc2c489",
  "armHelperFPAPrincipalId": "bc17c825-6cf8-40d0-8bd6-5536a993115e",
  "aroDevopsMsiId": "/subscriptions/1d3378d3-5a3f-4712-85a1-2485495dfc4b/resourceGroups/global/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aro-hcp-devops",
  "backend": {
    "imageTag": ""
  },
  "baseDnsZoneName": "hcp.osadev.cloud",
  "baseDnsZoneRG": "global",
  "clusterService": {
    "acrRG": "global",
    "azureOperatorsManagedIdentitiesConfig": "controlPlaneOperatorsIdentities:\n  cloud-controller-manager:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/ebe170ec-1247-536a-86d9-74c829dd9844'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Cloud Controller Manager - Dev'\n    optional: false\n  ingress:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/589ca160-4fac-501e-ad6c-006a19583727'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Cluster Ingress Operator - Dev'\n    optional: false\n  disk-csi-driver:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/4367fe74-0b43-5033-b629-15d9f28415ac'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Disk Storage Operator - Dev'\n    optional: false\n  file-csi-driver:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/fdc0aaaa-1c3e-548e-ad27-0321e5fab18b'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift File Storage Operator - Dev'\n    optional: false\n  image-registry:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/357b9263-656f-5d45-9d7a-ccb825f0683f'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Image Registry Operator - Dev'\n    optional: false\n  cloud-network-config:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/4e4f23fe-3fab-568b-a001-10b233b0f840'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Network Operator - Dev'\n    optional: false\ndataPlaneOperatorsIdentities:\n  disk-csi-driver:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/4367fe74-0b43-5033-b629-15d9f28415ac'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Disk Storage Operator - Dev'\n    k8sServiceAccounts:\n      - name: 'azure-disk-csi-driver-operator'\n        namespace: 'openshift-cluster-csi-drivers'\n      - name: 'azure-disk-csi-driver-controller-sa'\n        namespace: 'openshift-cluster-csi-drivers'\n    optional: false\n  image-registry:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/357b9263-656f-5d45-9d7a-ccb825f0683f'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Image Registry Operator - Dev'\n    k8sServiceAccounts:\n      - name: 'cluster-image-registry-operator'\n        namespace: 'openshift-image-registry'\n      - name: 'registry'\n        namespace: 'openshift-image-registry'\n    optional: false\n  file-csi-driver:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/fdc0aaaa-1c3e-548e-ad27-0321e5fab18b'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift File Storage Operator - Dev'\n    k8sServiceAccounts:\n      - name: 'azure-file-csi-driver-operator'\n        namespace: 'openshift-cluster-csi-drivers'\n      - name: 'azure-file-csi-driver-controller-sa'\n        namespace: 'openshift-cluster-csi-drivers'\n      - name: 'azure-file-csi-driver-node-sa'\n        namespace: 'openshift-cluster-csi-drivers'\n    optional: false\n  ingress:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/589ca160-4fac-501e-ad6c-006a19583727'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Cluster Ingress Operator - Dev'\n    k8sServiceAccounts:\n      - name: 'ingress-operator'\n        namespace: 'openshift-ingress-operator'\n    optional: false\n  cloud-network-config:\n    minOpenShiftVersion: 4.17\n    azureRoleDefinitionResourceId: '/providers/Microsoft.Authorization/roleDefinitions/4e4f23fe-3fab-568b-a001-10b233b0f840'\n    azureRoleDefinitionName: 'Azure Red Hat OpenShift Network Operator - Dev'\n    k8sServiceAccounts:\n      - name: 'cloud-network-config-controller'\n        namespace: 'openshift-cloud-network-config-controller'\n    optional: false\n",
    "imageRepo": "app-sre/uhc-clusters-service",
    "imageTag": "6157c57",
    "postgres": {
      "deploy": true,
      "minTLSVersion": "TLSV1.2",
      "name": "arohcp-cs-dev",
      "private": false
    }
  },
  "cxKeyVault": {
    "name": "arohcp-cx-dev-1",
    "private": false,
    "softDelete": false
  },
  "extraVars": {},
  "firstPartyAppClientId": "57e54810-3138-4f38-bd3b-29cb33f4c358",
  "frontend": {
    "cert": {
      "name": "frontend-cert-dev"
    },
    "cosmosDB": {
      "deploy": true,
      "disableLocalAuth": true,
      "name": "arohcp-rp-dev",
      "private": false
    },
    "imageTag": ""
  },
  "global": {
    "manageTokenCustomRole": true,
    "region": "westus3",
    "rg": "global",
    "subscription": "hcp-westus3"
  },
  "hypershift": {
    "additionalInstallArg": "--tech-preview-no-upgrade",
    "namespace": "hypershift"
  },
  "hypershiftOperator": {
    "imageTag": "9aca808"
  },
  "imageSync": {
    "acrRG": "global",
    "componentSync": {
      "bearerSecretNames": [
        "bearer-secret"
      ],
      "enabled": true,
      "imageRepo": "image-sync/component-sync",
      "imageTag": "latest",
      "repositories": "quay.io/acm-d/rhtap-hypershift-operator,quay.io/app-sre/uhc-clusters-service,quay.io/package-operator/package-operator-package",
      "secrets": "{\"secrets\":[{\"registry\": \"quay.io\", \"secretfile\": \"/auth/bearer-secret\"}]}"
    },
    "environmentName": "aro-hcp-image-sync",
    "keyVault": {
      "name": "arohcp-imagesync-dev",
      "private": false,
      "softDelete": false
    },
    "ocMirror": {
      "enabled": true,
      "imageRepo": "image-sync/oc-mirror",
      "imageTag": "0b3c08f"
    },
    "rg": "hcp-underlay-westus3-imagesync-dev"
  },
  "istioVersion": "asm-1-22",
  "kubernetesVersion": "1.30.6",
  "maestro": {
    "certDomain": "selfsigned.maestro.keyvault.azure.com",
    "consumerName": "hcp-underlay-dev-mgmt-1",
    "eventGrid": {
      "maxClientSessionsPerAuthName": 4,
      "name": "arohcp-maestro-dev",
      "private": false
    },
    "imageBase": "quay.io/redhat-user-workloads/maestro-rhtap-tenant/maestro/maestro",
    "imageTag": "bc2f131579c6ffc664c15f48c50a9936f1b4a7ce",
    "postgres": {
      "deploy": false,
      "minTLSVersion": "TLSV1.2",
      "name": "arohcp-maestro-dev",
      "private": false,
      "serverStorageSizeGB": 32,
      "serverVersion": "15"
    },
    "restrictIstioIngress": true,
    "serverMqttClientName": "maestro-server-dev-dev"
  },
  "mgmt": {
    "clusterServiceResourceId": "/subscriptions/1d3378d3-5a3f-4712-85a1-2485495dfc4b/resourcegroups/hcp-underlay-dev-svc/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clusters-service",
    "etcd": {
      "kvName": "arohcp-etcd-dev-1",
      "kvSoftDelete": false
    },
    "rg": "hcp-underlay-dev-mgmt-1",
    "subscription": "ARO Hosted Control Planes (EA Subscription 1)",
    "systemAgentPool": {
      "maxCount": 4,
      "minCount": 1,
      "osDiskSizeGB": 32,
      "vmSize": "Standard_D2s_v3"
    },
    "userAgentPool": {
      "azCount": 3,
      "maxCount": 12,
      "minCount": 2,
      "osDiskSizeGB": 100,
      "vmSize": "Standard_D4s_v3"
    }
  },
  "mgmtKeyVault": {
    "name": "arohcp-mgmt-dev-1",
    "private": false,
    "softDelete": false
  },
  "miMockClientId": "4daa4e3b-abc1-4f9c-812c-77bd37e06741",
  "miMockPrincipalId": "a03f690c-4b2e-4eef-841e-f1904efe0e37",
  "monitoring": {
    "grafanaAdminGroupPrincipalId": "6b6d3adf-8476-4727-9812-20ffdef2b85c",
    "grafanaName": "arohcp-dev",
    "msiName": "aro-hcp-metrics-msi-dev",
    "workspaceName": "arohcp-dev"
  },
  "msiKeyVault": {
    "name": "arohcp-msi-dev-1",
    "private": false,
    "softDelete": false
  },
  "ocpAcrName": "arohcpocpdev",
  "oidcStorageAccountName": "arohcpoidcdev",
  "podSubnetPrefix": "10.128.64.0/18",
  "region": "westus3",
  "regionRG": "hcp-underlay-dev",
  "regionalDNSSubdomain": "westus3",
  "serviceKeyVault": {
    "name": "aro-hcp-dev-svc-kv",
    "private": false,
    "region": "westus3",
    "rg": "global",
    "softDelete": true
  },
  "subnetPrefix": "10.128.8.0/21",
  "svc": {
    "etcd": {
      "kvName": "arohcp-etcd-dev",
      "kvSoftDelete": false
    },
    "rg": "hcp-underlay-dev-svc",
    "subscription": "ARO Hosted Control Planes (EA Subscription 1)",
    "userAgentPool": {
      "azCount": 3,
      "maxCount": 3,
      "minCount": 1,
      "osDiskSizeGB": 32,
      "vmSize": "Standard_D2s_v3"
    }
  },
  "svcAcrName": "arohcpsvcdev",
  "vnetAddressPrefix": "10.128.0.0/14"
}
