=== katherinelc321/ARO-HCP/config/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "object",
    "properties": {
      "aksName": {
        "type": "string"
      },
      "aroDevopsMsiId": {
        "type": "string"
      },
      "baseDnsZoneName": {
        "type": "string"
      },
      "baseDnsZoneRG": {
        "type": "string"
      },
      "clusterService": {
        "type": "object",
        "properties": {
          "acrRG": {
            "type": "string"
          },
          "imageRepo": {
            "type": "string"
          },
          "imageTag": {
            "type": "string"
          },
          "postgres": {
            "type": "object",
            "properties": {
              "deploy": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              },
              "minTLSVersion": {
                "type": "string",
                "enum": ["TLSV1.2", "TLSV1.3"]
              }
            },
            "required": [
              "deploy",
              "name",
              "private",
              "minTLSVersion"
            ]
          },
          "azureOperatorsManagedIdentitiesConfig":{
            "type": "string" 
          }
        },
        "additionalProperties": false,
        "required": [
          "acrRG",
          "imageRepo",
          "imageTag",
          "postgres"
        ]
      },
      "cxKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "softDelete"
        ]
      },
      "extraVars": {
        "type": "object",
        "properties": {},
        "required": []
      },
      "firstPartyAppClientId": {
        "type": "string"
      },
      "miMockClientId": {
        "type": "string"
      },
      "miMockPrincipalId": {
        "type": "string"
      },
      "armHelperClientId": {
        "type": "string"
      },
      "armHelperFPAPrincipalId": {
        "type": "string"
      },
      "backend": {
        "type": "object",
        "properties": {
          "imageTag": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "imageTag"
        ]
      },
      "frontend": {
        "type": "object",
        "properties": {
          "imageTag": {
            "type": "string"
          },
          "cosmosDB": {
            "type": "object",
            "properties": {
              "deploy": {
                "type": "boolean"
              },
              "disableLocalAuth": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "deploy",
              "disableLocalAuth",
              "name",
              "private"
            ]
          },
          "cert": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "name"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "imageTag",
          "cosmosDB",
          "cert"
        ]
      },
      "global": {
        "type": "object",
        "properties": {
          "rg": {
            "type": "string"
          },
          "subscription": {
            "type": "string"
          },
          "manageTokenCustomRole": {
            "type": "boolean"
          },
          "region": {
            "type": "string"
          }
        },
        "required": [
          "rg",
          "subscription",
          "manageTokenCustomRole",
          "region"
        ]
      },
      "hypershift": {
        "type": "object",
        "properties": {
          "additionalInstallArg": {
            "type": "string"
          },
          "namespace": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "additionalInstallArg",
          "namespace"
        ]
      },
      "hypershiftOperator": {
        "type": "object",
        "properties": {
          "imageTag": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "imageTag"
        ]
      },
      "imageSync": {
        "type": "object",
        "properties": {
          "acrRG": {
            "type": "string"
          },
          "environmentName": {
            "type": "string"
          },
          "componentSync": {
            "type": "object",
            "properties": {
              "bearerSecretNames": {
                "type": "array"
              },
              "enabled": {
                "type": "boolean"
              },
              "imageRepo": {
                "type": "string"
              },
              "imageTag": {
                "type": "string"
              },
              "repositories": {
                "type": "string"
              },
              "secrets": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "bearerSecretNames",
              "enabled",
              "imageRepo",
              "imageTag",
              "repositories",
              "secrets"
            ]
          },
          "ocMirror": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean"
              },
              "imageRepo": {
                "type": "string"
              },
              "imageTag": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "enabled",
              "imageRepo",
              "imageTag"
            ]
          },
          "keyVault": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              },
              "softDelete": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "name",
              "private",
              "softDelete"
            ]
          },
          "rg": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "acrRG",
          "environmentName",
          "componentSync",
          "ocMirror",
          "keyVault",
          "rg"
        ]
      },
      "istioVersion": {
        "type": "string"
      },
      "kubernetesVersion": {
        "type": "string"
      },
      "maestro": {
        "type": "object",
        "properties": {
          "certDomain": {
            "type": "string"
          },
          "consumerName": {
            "type": "string"
          },
          "serverMqttClientName": {
            "type": "string"
          },
          "eventGrid": {
            "type": "object",
            "properties": {
              "maxClientSessionsPerAuthName": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "maxClientSessionsPerAuthName",
              "name",
              "private"
            ]
          },
          "imageBase": {
            "type": "string"
          },
          "imageTag": {
            "type": "string"
          },
          "postgres": {
            "type": "object",
            "properties": {
              "deploy": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "private": {
                "type": "boolean"
              },
              "serverStorageSizeGB": {
                "type": "integer"
              },
              "serverVersion": {
                "type": "string"
              },
              "minTLSVersion": {
                "type": "string",
                "enum": ["TLSV1.2", "TLSV1.3"]
              }
            },
            "additionalProperties": false,
            "required": [
              "deploy",
              "name",
              "private",
              "serverStorageSizeGB",
              "serverVersion",
              "minTLSVersion"
            ]
          },
          "restrictIstioIngress": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "certDomain",
          "consumerName",
          "serverMqttClientName",
          "eventGrid",
          "imageBase",
          "imageTag",
          "postgres",
          "restrictIstioIngress"
        ]
      },
      "mgmt": {
        "type": "object",
        "properties": {
          "etcd": {
            "type": "object",
            "properties": {
              "kvName": {
                "type": "string"
              },
              "kvSoftDelete": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "kvName",
              "kvSoftDelete"
            ]
          },
          "rg": {
            "type": "string"
          },
          "subscription": {
            "type": "string"
          },
          "clusterServiceResourceId": {
            "type": "string"
          },
          "systemAgentPool": {
            "type": "object",
            "properties": {
              "maxCount": {
                "type": "number"
              },
              "minCount": {
                "type": "number"
              },
              "osDiskSizeGB": {
                "type": "number"
              },
              "vmSize": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "maxCount",
              "minCount",
              "osDiskSizeGB",
              "vmSize"
            ]
          },
          "userAgentPool": {
            "type": "object",
            "properties": {
              "azCount": {
                "type": "number"
              },
              "maxCount": {
                "type": "number"
              },
              "minCount": {
                "type": "number"
              },
              "osDiskSizeGB": {
                "type": "number"
              },
              "vmSize": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "azCount",
              "maxCount",
              "minCount",
              "osDiskSizeGB",
              "vmSize"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "clusterServiceResourceId",
          "etcd",
          "rg",
          "systemAgentPool",
          "subscription",
          "userAgentPool"
        ]
      },
      "mgmtKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "softDelete"
        ]
      },
      "monitoring": {
        "type": "object",
        "properties": {
          "grafanaAdminGroupPrincipalId": {
            "type": "string"
          },
          "grafanaName": {
            "type": "string"
          },
          "msiName": {
            "type": "string"
          },
          "workspaceName": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "grafanaAdminGroupPrincipalId",
          "grafanaName",
          "msiName",
          "workspaceName"
        ]
      },
      "msiKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "softDelete"
        ]
      },
      "ocpAcrName": {
        "type": "string"
      },
      "oidcStorageAccountName": {
        "type": "string"
      },
      "podSubnetPrefix": {
        "type": "string"
      },
      "region": {
        "type": "string"
      },
      "regionRG": {
        "type": "string"
      },
      "regionalDNSSubdomain": {
        "type": "string"
      },
      "serviceKeyVault": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "region": {
            "type": "string"
          },
          "rg": {
            "type": "string"
          },
          "softDelete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "private",
          "region",
          "rg",
          "softDelete"
        ]
      },
      "subnetPrefix": {
        "type": "string"
      },
      "svc": {
        "type": "object",
        "properties": {
          "etcd": {
            "type": "object",
            "properties": {
              "kvName": {
                "type": "string"
              },
              "kvSoftDelete": {
                "type": "boolean"
              }
            },
            "additionalProperties": false,
            "required": [
              "kvName",
              "kvSoftDelete"
            ]
          },
          "userAgentPool": {
            "type": "object",
            "properties": {
              "azCount": {
                "type": "number"
              },
              "maxCount": {
                "type": "number"
              },
              "minCount": {
                "type": "number"
              },
              "osDiskSizeGB": {
                "type": "number"
              },
              "vmSize": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "azCount",
              "maxCount",
              "minCount",
              "osDiskSizeGB",
              "vmSize"
            ]
          },
          "rg": {
            "type": "string"
          },
          "subscription": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "etcd",
          "rg",
          "subscription",
          "userAgentPool"
        ]
      },
      "svcAcrName": {
        "type": "string"
      },
      "vnetAddressPrefix": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": [
      "aksName",
      "aroDevopsMsiId",
      "baseDnsZoneName",
      "baseDnsZoneRG",
      "clusterService",
      "cxKeyVault",
      "firstPartyAppClientId",
      "frontend",
      "global",
      "hypershift",
      "hypershiftOperator",
      "imageSync",
      "istioVersion",
      "kubernetesVersion",
      "maestro",
      "mgmt",
      "mgmtKeyVault",
      "monitoring",
      "msiKeyVault",
      "ocpAcrName",
      "oidcStorageAccountName",
      "podSubnetPrefix",
      "region",
      "regionRG",
      "regionalDNSSubdomain",
      "serviceKeyVault",
      "subnetPrefix",
      "svc",
      "svcAcrName",
      "vnetAddressPrefix"
    ]
  }

=== katherinelc321/ARO-HCP/config/public-cloud-msft-int.json
{
  "aksName": "aro-hcp-aks",
  "armHelperClientId": "",
  "armHelperFPAPrincipalId": "",
  "aroDevopsMsiId": "/subscriptions/5299e6b7-b23b-46c8-8277-dc1147807117/resourcegroups/global-shared-resources/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aroint-int-public-oidc",
  "backend": {
    "imageTag": "0b3c08f"
  },
  "baseDnsZoneName": "aroapp-hcp.azure-test.net",
  "baseDnsZoneRG": "global-shared-resources",
  "clusterService": {
    "acrRG": "global-shared-resources",
    "imageRepo": "app-sre/uhc-clusters-service",
    "imageTag": "ecd15ad",
    "postgres": {
      "deploy": true,
      "minTLSVersion": "TLSV1.2",
      "name": "arohcp-cs-int",
      "private": false
    }
  },
  "cxKeyVault": {
    "name": "arohcp-cx-int-1",
    "private": false,
    "softDelete": false
  },
  "extraVars": {},
  "firstPartyAppClientId": "??? the one used by CS to do first party stuff ???",
  "frontend": {
    "cert": {
      "name": "frontend-cert-int"
    },
    "cosmosDB": {
      "deploy": true,
      "disableLocalAuth": true,
      "name": "arohcp-rp-int",
      "private": false
    },
    "imageTag": "0b3c08f"
  },
  "global": {
    "manageTokenCustomRole": false,
    "region": "uksouth",
    "rg": "global-shared-resources",
    "subscription": "hcp-westus3"
  },
  "hypershift": {
    "additionalInstallArg": "--tech-preview-no-upgrade",
    "namespace": "hypershift"
  },
  "hypershiftOperator": {
    "imageTag": "9aca808"
  },
  "imageSync": {
    "acrRG": "global-shared-resources",
    "componentSync": {
      "bearerSecretNames": [],
      "enabled": true,
      "imageRepo": "image-sync/component-sync",
      "imageTag": "0b3c08f",
      "repositories": "quay.io/acm-d/rhtap-hypershift-operator,quay.io/app-sre/uhc-clusters-service,quay.io/package-operator/package-operator-package",
      "secrets": "{\"secrets\":[{\"registry\": \"quay.io\", \"secretfile\": \"/auth/${pullSecretFile}\"}]}"
    },
    "environmentName": "global-shared-resources",
    "keyVault": {
      "name": "arohcp-imagesync-int",
      "private": false,
      "softDelete": true
    },
    "ocMirror": {
      "enabled": true,
      "imageRepo": "image-sync/oc-mirror",
      "imageTag": "0b3c08f"
    },
    "rg": "hcp-underlay-imagesync"
  },
  "istioVersion": "asm-1-22",
  "kubernetesVersion": "1.30.6",
  "maestro": {
    "certDomain": "selfsigned.maestro.keyvault.azure.com",
    "consumerName": "hcp-underlay-int-mgmt-1",
    "eventGrid": {
      "maxClientSessionsPerAuthName": 4,
      "name": "arohcp-maestro-int",
      "private": false
    },
    "imageBase": "quay.io/redhat-user-workloads/maestro-rhtap-tenant/maestro/maestro",
    "imageTag": "bc2f131579c6ffc664c15f48c50a9936f1b4a7ce",
    "postgres": {
      "deploy": false,
      "minTLSVersion": "TLSV1.2",
      "name": "arohcp-maestro-int",
      "private": false,
      "serverStorageSizeGB": 32,
      "serverVersion": "15"
    },
    "restrictIstioIngress": true,
    "serverMqttClientName": "maestro-server"
  },
  "mgmt": {
    "clusterServiceResourceId": "todo",
    "etcd": {
      "kvName": "arohcp-etcd-int-1",
      "kvSoftDelete": true
    },
    "rg": "hcp-underlay-westus3-mgmt-1",
    "subscription": "hcp-westus3",
    "systemAgentPool": {
      "maxCount": 4,
      "minCount": 1,
      "osDiskSizeGB": 32,
      "vmSize": "Standard_D2s_v3"
    },
    "userAgentPool": {
      "azCount": 3,
      "maxCount": 12,
      "minCount": 2,
      "osDiskSizeGB": 100,
      "vmSize": "Standard_D4s_v3"
    }
  },
  "mgmtKeyVault": {
    "name": "arohcp-mgmt-int-1",
    "private": false,
    "softDelete": false
  },
  "miMockClientId": "",
  "miMockPrincipalId": "",
  "monitoring": {
    "grafanaAdminGroupPrincipalId": "2fdb57d4-3fd3-415d-b604-1d0e37a188fe",
    "grafanaName": "arohcp-int",
    "msiName": "aro-hcp-metrics-msi-int",
    "workspaceName": "arohcp-int"
  },
  "msiKeyVault": {
    "name": "arohcp-msi-int-1",
    "private": false,
    "softDelete": false
  },
  "ocpAcrName": "arohcpocpint",
  "oidcStorageAccountName": "arohcpoidcintint",
  "podSubnetPrefix": "10.128.64.0/18",
  "region": "westus3",
  "regionRG": "westus3-shared-resources",
  "regionalDNSSubdomain": "westus3",
  "serviceKeyVault": {
    "name": "arohcp-svc-int",
    "private": false,
    "region": "westus3",
    "rg": "hcp-underlay-westus3-svc",
    "softDelete": false
  },
  "subnetPrefix": "10.128.8.0/21",
  "svc": {
    "etcd": {
      "kvName": "arohcp-etcd-int",
      "kvSoftDelete": true
    },
    "rg": "hcp-underlay-westus3-svc",
    "subscription": "hcp-westus3",
    "userAgentPool": {
      "azCount": 3,
      "maxCount": 3,
      "minCount": 1,
      "osDiskSizeGB": 32,
      "vmSize": "Standard_D2s_v3"
    }
  },
  "svcAcrName": "arohcpsvcint",
  "vnetAddressPrefix": "10.128.0.0/14"
}
